/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Poupanca;

import RegraDeNegocio.Poupanca;
import RegraDeNegocio.Usuario;



/**
 *
 * @author Senai
 */
public class EditarContapp extends javax.swing.JFrame {
    
    private Poupanca p;

    public Poupanca getAg() {
        Poupanca p = null;
        return p;
    }

    public void setU(Poupanca p) {
        this.p = p;   
    }

    /**
     * Creates new form EditarContapp
     */
    public EditarContapp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btcadastrarpoupanca = new javax.swing.JButton();
        txtEditarContaPP = new javax.swing.JTextField();
        txtEditarCliente = new javax.swing.JComboBox<>();
        txtEditarAgencia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Conta Poupança");
        getContentPane().setLayout(null);

        btcadastrarpoupanca.setText("Cadastrar");
        btcadastrarpoupanca.setAutoscrolls(true);
        btcadastrarpoupanca.setDoubleBuffered(true);
        btcadastrarpoupanca.setFocusCycleRoot(true);
        btcadastrarpoupanca.setHideActionText(true);
        btcadastrarpoupanca.setInheritsPopupMenu(true);
        btcadastrarpoupanca.setSelected(true);
        btcadastrarpoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarpoupancaActionPerformed(evt);
            }
        });
        getContentPane().add(btcadastrarpoupanca);
        btcadastrarpoupanca.setBounds(299, 371, 213, 40);

        txtEditarContaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarContaPPActionPerformed(evt);
            }
        });
        getContentPane().add(txtEditarContaPP);
        txtEditarContaPP.setBounds(458, 226, 477, 22);

        txtEditarCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEditarCliente);
        txtEditarCliente.setBounds(299, 174, 636, 22);

        txtEditarAgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(txtEditarAgencia);
        txtEditarAgencia.setBounds(299, 226, 136, 22);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Editar Poupança");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(539, 69, 200, 54);

        jLabel2.setText("Nome do Cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(299, 151, 99, 16);

        jLabel4.setText("Numero da Conta:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(458, 203, 105, 16);

        jLabel3.setText("Agência:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(299, 203, 50, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pppppp.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 990, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcadastrarpoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarpoupancaActionPerformed

      

        
    }//GEN-LAST:event_btcadastrarpoupancaActionPerformed

    private void txtEditarContaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarContaPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarContaPPActionPerformed

    private void txtEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarClienteActionPerformed

    }//GEN-LAST:event_txtEditarClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastrarpoupanca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> txtEditarAgencia;
    private javax.swing.JComboBox<String> txtEditarCliente;
    private javax.swing.JTextField txtEditarContaPP;
    // End of variables declaration//GEN-END:variables
}
